import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import 'react-toastify/ReactToastify.min.css'

const roboto = Roboto({ subsets: ['latin'], weight: "300" })

export const metadata: Metadata = {
  title: 'Music Listener',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
